
project_id = "wkmhgfurujsvgckunpgy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.signup-options]
verify_jwt = false

[functions.calendar-admin-email]
verify_jwt = true

[functions.consultant-availability]
verify_jwt = true
