# Quick Railway Debug Script
# Run this in your local terminal to check Railway logs

Write-Host "=== Railway Log Debugging Script ==="
Write-Host ""
Write-Host "1. Go to railway.app and login"
Write-Host "2. Select your project"
Write-Host "3. Click on your backend service" 
Write-Host "4. Go to 'Deployments' tab"
Write-Host "5. Click latest deployment"
Write-Host "6. Click 'View Logs'"
Write-Host ""
Write-Host "=== Look for these messages when someone registers ==="
Write-Host "✅ [DEBUG] EmailSettings EnableEmailVerification parsed to: True"
Write-Host "✅ [DEBUG] Email sent successfully to: user@email.com"
Write-Host "❌ [DEBUG] Email send failed: [error message]"
Write-Host ""
Write-Host "=== If no email debug messages appear ==="
Write-Host "The EmailSettings environment variables are not configured correctly"
Write-Host ""
Write-Host "Required Railway Environment Variables:"
Write-Host "EmailSettings__EnableEmailVerification=true"
Write-Host "EmailSettings__RequireEmailVerification=true" 
Write-Host "EmailSettings__EmailVerificationTokenExpiryHours=24"
Write-Host "BREVO_API_KEY=your_brevo_api_key_here"
Write-Host "Brevo__ApiKey=your_brevo_api_key_here"
Write-Host "Brevo__FromEmail=noreply@yuktor.com"
Write-Host "Brevo__FromName=Yuktor SAP BASIS Support"
Write-Host "FrontendUrl=https://app.yuktor.com"
Write-Host ""
Write-Host "=== Test Steps ==="
Write-Host "1. Add missing environment variables to Railway"
Write-Host "2. Redeploy the service"
Write-Host "3. Try registering a new user"
Write-Host "4. Check logs immediately after registration"