// This file is automatically generated. Do not edit it directly.
// During local development we replace the real Supabase client with a shim
// that forwards calls to our .NET API. This keeps the app behavior the same
// while avoiding external Supabase requests.
import { supabase } from './shim';

export { supabase };