// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkmhgfurujsvgckunpgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrbWhnZnVydWpzdmdja3VucGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTc3MjgsImV4cCI6MjA2NTc5MzcyOH0.r6snhBhwuKAZuORjojbdyNhrn9_Dy4xAInpcFafjJEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);